jdbc:
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/thorough?useSSL=false&useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456
  testSql: SELECT 'x' FROM DUAL

redis:
  redisCache: single
  master: kkk

shiro:
  shiroName: 111

server:
  port: 8080

pathology:
  os:
    separator: /
  image:
    openslide:
      jni-so: /usr/local/lib/openslide-java/libthoslide-jni.so
    auto-stamp:
      url: /pathology/label/
    quantity: 0.9
    isZip: true
  zookeeper:
    connect: zookeeper:2181
  kafka:
    broker:
      list: kafka:9092
    producer:
      topic: job_submit
      cancel: job_cancel
    consumer:
      topic: job_progress
  page:
      pageSize: 20
  label:
        strategy: 1

breakpoint:
  upload:
    dir: /opt/pathology/fileupload/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880
  hdfs: hdfs://localhost:8020

logging:
  backup: /Users/chenlinsong
  path: logs

image:
  label:
    cache: /opt/pathology/image/label/cache

prediction:
  server: http://192.168.31.100:8081/insights/pathology/image/saveImageAndImageUser
