spring:
  application:
    name: pathology
#  freemarker:
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    allow-request-override: true
#    allow-session-override: true
#    expose-spring-macro-helpers: true
#    request-context-attribute: request
#    suffix: .ftl
  http:
    multipart:
      max-file-size: 5000MB
      max-request-size: 100000MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
      favicon:
        enabled: false
jdbc:
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://192.168.31.100:3306/thorough?useSSL=false&useUnicode=true&characterEncoding=utf-8
  username: root
  password: 123456

redis:
  keyPrefix: thorough
  host: 192.168.31.100
  port: 26379
  master: master6379
  redisCache: devCluster

server:
  port: 8088
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json,application/javascript
    min-response-size: 2048
#  display-name: PathologyApplication
#  session:
#    timeout: 86400
#  tomcat:
#    uri-encoding: UTF-8

flyway:
  enabled: false


pathology:
  os:
    separator: /
  image:
    kfb:
      jni-so: /home/iiis/chenlinsong/c-lib/libkfbImage-jni.so
      shell: /home/iiis/chenlinsong/c-lib/kfbImageHeader
    openslide:
      jni-so: /usr/local/lib/openslide-java/libthoslide-jni.so
    auto-stamp:
      url: /pathology/label/
    quantity: 0.9
    isZip: true
  user:
    default-pwd: 12345qwert
  zookeeper:
    connect: 192.168.31.101:2181,192.168.31.102:2181,192.168.31.100:2181
  kafka:
    broker:
      list: 192.168.31.101:9092,192.168.31.102:9092,192.168.31.100:9092
    producer:
      topic: job_submit
      cancel: job_cancel
    consumer:
      topic: job_progress
  page:
      pageSize: 20
  label:
        strategy: 1

breakpoint:
  upload:
    dir: /opt/pathology/fileupload/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880
  hdfs: hdfs://localhost:8020


logging:
  backup: /opt/pathology/backup/
  path: /opt/pathology/logs




#/usr/local/lib/openslide-java/libopenslide-jni.jnilib