spring:
  application:
    name: pathology
#  freemarker:
#    cache: false
#    charset: UTF-8
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    allow-request-override: true
#    allow-session-override: true
#    expose-spring-macro-helpers: true
#    request-context-attribute: request
#    suffix: .ftl
  http:
    multipart:
      max-file-size: 5000MB
      max-request-size: 100000MB
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  mvc:
      favicon:
        enabled: false

jdbc:
  type: mysql
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://10.1.0.186:8010/thorough?useSSL=false&useUnicode=true&characterEncoding=utf-8
  username: root
  password: 5MOh0U5Kp8yk

redis:
  keyPrefix: thorough
  host: 10.1.0.250
  port: 16800
  master: master
  redisCache: onlineCluster

server:
  port: 50000
  compression:
    enabled: true
    mime-types: text/html,text/css,application/json,application/javascript
    min-response-size: 2048
  display-name: PathologyApplication
  session:
    timeout: 86400
  tomcat:
    uri-encoding: UTF-8

flyway:
  enabled: false


pathology:
  os:
    separator: /
  image:
    kfb:
      jni-so: /home/c-lib/libkfbImage-jni.so
      shell: /home/c-lib/kfbImageHeader
    openslide:
      jni-so: /usr/local/lib/openslide-java/libthoslide-jni.so
    auto-stamp:
      url: /pathology/label/
    quantity: 0.9
    isZip: true
  user:
    default-pwd: 12345qwert
  zookeeper:
    connect: 10.1.0.187:12181,10.1.0.188:12181,10.1.0.190:12181
  kafka:
    broker:
      list: 10.1.0.187:19092,10.1.0.188:19092,10.1.0.190:19092
    producer:
      topic: job_submit
      cancel: job_cancel
    consumer:
      topic: job_progress
  page:
      pageSize: 20
  label:
        strategy: 1

breakpoint:
  upload:
    dir: /opt/pathology/fileupload/
    #1024*1024=1 048 576,5M=5 242 880
    chunkSize: 5 242 880
  hdfs: hdfs://localhost:8020

logging:
  path: /opt/pathology/logs

image:
  label:
    cache: /opt/pathology/image/label/cache

---

spring:
  profiles: test

pathology:
  image:
    root-path: /home/pathology/slide-image/
    kfb:
      jni-so: /home/pathology/c-lib/libkfbImage-jni.so
      shell: /home/pathology/c-lib/getKfbImageHeader.sh
    openslide:
      jni-so: /home/pathology/c-lib/libopenslide-jni.so
    auto-stamp:
      url: https://427194aa.ngrok.io/sys/
---

spring:
  profiles: iiis

pathology:
  image:
    root-path: /home/iiis/slide-image/
    auto-stamp:
      url: http://localhost:8080/sys/

logging:
  backup: /opt/pathology/backup/
  path: logs



#/usr/local/lib/openslide-java/libopenslide-jni.jnilib